// Gerado manualmente (por IA, sem API externa) — área 2 (Obrigações)
// Baseado no texto real dos artigos 233-420 do CC, extraído de vade_artigos.
// REVISAR antes de colar no array "banco" de seed/questoes.js.

[2,'Três devedores (A, B e C) são solidariamente obrigados perante um credor por uma dívida de R$ 30.000,00. O credor pode exigir o pagamento integral de apenas um dos devedores?',
 'Art. 275 CC — o credor tem direito a exigir e receber de um ou de alguns dos devedores, parcial ou totalmente, a dívida comum. Na solidariedade passiva, cada devedor responde pela dívida toda, cabendo depois ao que pagou o direito de regresso contra os demais (art. 283).','facil',
 [['A','Sim, pode exigir de um só devedor o pagamento integral da dívida',true],['B','Não, deve necessariamente dividir a cobrança entre os três devedores',false],['C','Só pode exigir o total se os três forem citados no mesmo processo',false],['D','Não, a solidariedade passiva presume-se apenas quando prevista em contrato escrito',false]]],

[2,'Marcos cede seu crédito contra Bruno para Carla, mas Bruno não é notificado da cessão. Sem saber da cessão, Bruno paga a dívida diretamente a Marcos (credor originário). Esse pagamento:',
 'Arts. 290 e 292 CC — a cessão do crédito não tem eficácia em relação ao devedor, senão quando a este notificada; fica desobrigado o devedor que, antes de ter conhecimento da cessão, paga ao credor primitivo. Bruno pagou de boa-fé, sem notificação, então está exonerado.','medio',
 [['A','É válido e exonera Bruno, pois ele não havia sido notificado da cessão',true],['B','É nulo, pois a cessão já havia transferido o crédito a Carla',false],['C','É válido, mas Bruno terá que pagar novamente a Carla',false],['D','Depende de registro público da cessão para ter qualquer efeito',false]]],

[2,'Um contrato prevê o pagamento de quantia certa em data determinada. Chegada a data, o devedor não paga. Para que se configure a mora do devedor nesse caso, é necessária a interpelação (notificação) do credor?',
 'Art. 397, caput, CC — o inadimplemento da obrigação positiva e líquida, no seu termo, constitui de pleno direito em mora o devedor (mora ex re). Não é necessária qualquer interpelação: o vencimento do prazo já opera a mora automaticamente ("dies interpellat pro homine").','medio',
 [['A','Sim, sem interpelação judicial ou extrajudicial não há mora',false],['B','Não, a mora se constitui de pleno direito com o vencimento do termo',true],['C','Sim, mas apenas se a obrigação for de valor superior a determinado limite',false],['D','Não, mas somente se o contrato expressamente dispensar a interpelação',false]]],

[2,'Em contrato de R$ 100.000,00, as partes estipulam cláusula penal de R$ 150.000,00 para o caso de inadimplemento total. O devedor cumpre metade da obrigação e depois descumpre o restante. Nessa hipótese, o Código Civil autoriza que:',
 'Arts. 412 e 413 CC — o valor da cominação imposta na cláusula penal não pode exceder o da obrigação principal (aqui, o teto seria R$ 100.000,00); além disso, a penalidade deve ser reduzida equitativamente pelo juiz quando a obrigação principal tiver sido cumprida em parte, ou quando o montante for manifestamente excessivo.','dificil',
 [['A','A cláusula penal seja aplicada integralmente, respeitada a autonomia da vontade',false],['B','O juiz reduza equitativamente a penalidade, observado o limite do valor da obrigação principal',true],['C','A cláusula penal seja considerada nula de pleno direito por exceder o valor principal',false],['D','O credor escolha livremente entre a cláusula penal e as perdas e danos, sem limite de valor',false]]],

[2,'Ana deve a Pedro uma quantia certa em dinheiro, já vencida. Pedro, por sua vez, deve a Ana o cumprimento de uma obrigação de fazer (pintar um retrato), também já vencida. Pode haver compensação entre essas duas dívidas?',
 'Art. 369 CC — a compensação efetua-se entre dívidas líquidas, vencidas e de coisas fungíveis. Embora ambas as dívidas estejam vencidas, a obrigação de fazer (pintar um retrato) não é fungível nem se confunde com dinheiro, faltando o requisito da fungibilidade recíproca das prestações.','medio',
 [['A','Sim, basta que ambas as dívidas estejam vencidas',false],['B','Sim, pois a compensação independe da natureza das prestações',false],['C','Não, pois falta o requisito da fungibilidade entre as prestações',true],['D','Não, pois a compensação exige sempre autorização judicial prévia',false]]],

[2,'Em contrato de compra e venda, as partes estipulam arras no ato da celebração, sem prever cláusula de direito de arrependimento. O comprador desiste do negócio. O vendedor (parte inocente) pode reter as arras e ainda pleitear indenização suplementar, provando prejuízo maior?',
 'Arts. 417 e 419 CC — sem cláusula de arrependimento, as arras são confirmatórias: em caso de inexecução, a parte inocente pode reter as arras (ou exigir a execução do contrato) e, provando maior prejuízo, pedir indenização suplementar, valendo as arras como taxa mínima. A vedação à indenização suplementar (art. 420) só se aplica quando há direito de arrependimento estipulado — o que não é o caso aqui.','dificil',
 [['A','Não, pois as arras sempre têm função exclusivamente indenizatória',false],['B','Não, pois a indenização suplementar só cabe em contratos de consumo',false],['C','Sim, mas apenas se o contrato for registrado em cartório',false],['D','Sim, pois sem cláusula de arrependimento as arras são confirmatórias, cabendo indenização suplementar se provado maior prejuízo',true]]],

[2,'Em contrato que estipula cláusula penal exclusivamente "para o caso de mora" (cláusula penal moratória), ocorrido o atraso do devedor, o credor pretende exigir simultaneamente a satisfação da pena convencionada E o cumprimento integral da obrigação principal. Segundo o art. 411 do CC, isso é possível?',
 'Art. 411 CC — quando se estipular a cláusula penal para o caso de mora, terá o credor o arbítrio de exigir a satisfação da pena cominada, juntamente com o desempenho da obrigação principal. É a cláusula penal moratória, cumulável com o cumprimento — diferente da cláusula penal compensatória (art. 410, para o inadimplemento total), que se converte em alternativa a benefício do credor (ou a pena, ou o cumprimento, nunca ambos).','dificil',
 [['A','Não, a cláusula penal, seja moratória ou compensatória, sempre substitui o cumprimento da obrigação',false],['B','Sim, pois a cláusula penal moratória pode ser exigida cumulativamente com o cumprimento da obrigação principal',true],['C','Não, o credor deve escolher entre a pena e o cumprimento, nunca ambos, qualquer que seja o tipo de cláusula',false],['D','Sim, mas apenas se o contrato for de adesão',false]]],

[2,'Um credor tem obrigação solidária contra três devedores (A, B e C). Promove citação judicial apenas contra A, interrompendo a prescrição em relação a ele. Já esgotado o prazo prescricional quanto a B e C, sem que contra eles tenha sido movida qualquer ação, o credor pretende cobrá-los, sustentando que a interrupção contra A aproveitaria a todos, por se tratar de obrigação solidária. Segundo o art. 204 do CC, esse argumento procede?',
 'Art. 204 CC — a interrupção da prescrição operada contra o co-devedor não prejudica aos demais coobrigados. Mesmo em obrigações solidárias, a interrupção da prescrição contra um dos devedores é pessoal a ele, não se estendendo automaticamente aos demais codevedores.','dificil',
 [['A','Procede, pois a solidariedade estende a todos os efeitos processuais praticados contra qualquer codevedor',false],['B','Não procede, pois a interrupção operada contra um codevedor não prejudica os demais coobrigados',true],['C','Procede, mas somente se a obrigação for indivisível, e não meramente solidária',false],['D','Não procede, pois a prescrição jamais pode ser interrompida em obrigações solidárias',false]]],
